# Generated by Django 6.0 on 2025-12-14 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Pontos')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='children.child', verbose_name='Aventureiro')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_created', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por')),
            ],
            options={
                'verbose_name': 'Lançamento de Pontos',
                'verbose_name_plural': 'Lançamentos de Pontos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['child', '-created_at'], name='points_poin_child_i_b0ce4d_idx')],
            },
        ),
    ]
