# Generated by Django 6.0 on 2025-12-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='option',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='option',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.CharField(blank=True, help_text='Opções separadas por vírgula (ex: P,M,G)', max_length=200),
        ),
    ]
