# Generated by Django 6.0 on 2026-01-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_fee_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='ID externo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Referência externa'),
        ),
    ]
