# Generated by Django 6.0 on 2025-12-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='financial_whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp financeiro'),
        ),
    ]
