# Generated by Django 6.0 on 2026-01-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_financial_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='user',
            name='financial_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone financeiro'),
        ),
    ]
