# Generated by Django 6.0 on 2026-01-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_financial_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/', verbose_name='Foto 3x4'),
        ),
    ]
