# Generated by Django 6.0 on 2025-12-13 22:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('class_group', models.CharField(blank=True, max_length=80, verbose_name='Turma/Unidade')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='ChildFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='child_faces/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='children.child', verbose_name='Aventureiro')),
            ],
            options={
                'verbose_name': 'Rosto do Aventureiro',
                'verbose_name_plural': 'Rostos do Aventureiro',
            },
        ),
        migrations.CreateModel(
            name='GuardianChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, max_length=50, verbose_name='Vínculo')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='children.child', verbose_name='Aventureiro')),
                ('guardian_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Vínculo Responsável',
                'verbose_name_plural': 'Vínculos Responsáveis',
                'unique_together': {('guardian_user', 'child')},
            },
        ),
    ]
