# Generated by Django 6.0 on 2025-12-16 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_child_fee_discount_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sexo'),
        ),
        migrations.CreateModel(
            name='ChildHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('medications', models.TextField(blank=True, verbose_name='Medicamentos de uso contínuo')),
                ('restrictions', models.TextField(blank=True, verbose_name='Restrições médicas')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('emergency_contact', models.CharField(blank=True, max_length=150, verbose_name='Contato de emergência')),
                ('emergency_phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone de emergência')),
                ('health_plan', models.CharField(blank=True, max_length=120, verbose_name='Plano de saúde')),
                ('auth_activity', models.BooleanField(default=False, verbose_name='Autoriza atividades')),
                ('auth_medical', models.BooleanField(default=False, verbose_name='Autoriza atendimento médico')),
                ('auth_rules', models.BooleanField(default=False, verbose_name='Aceita regulamento')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='children.child')),
            ],
        ),
    ]
