# Generated by Django 6.0 on 2026-01-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_child_cpf_child_gender_childhealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='Certidão de nascimento'),
        ),
        migrations.AddField(
            model_name='child',
            name='father_absent',
            field=models.BooleanField(default=False, verbose_name='Pai ausente/desconhecido'),
        ),
        migrations.AddField(
            model_name='child',
            name='father_cpf',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF do pai'),
        ),
        migrations.AddField(
            model_name='child',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do pai'),
        ),
        migrations.AddField(
            model_name='child',
            name='father_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone do pai'),
        ),
        migrations.AddField(
            model_name='child',
            name='mother_absent',
            field=models.BooleanField(default=False, verbose_name='Mãe ausente/desconhecida'),
        ),
        migrations.AddField(
            model_name='child',
            name='mother_cpf',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF da mãe'),
        ),
        migrations.AddField(
            model_name='child',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome da mãe'),
        ),
        migrations.AddField(
            model_name='child',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone da mãe'),
        ),
    ]
