# Generated by Django 6.0 on 2025-12-14 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('required', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('validity_days', models.IntegerField(blank=True, null=True, verbose_name='Validade (dias)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChildDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('VENCIDO', 'Vencido'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Recebido em')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido até')),
                ('note', models.TextField(blank=True, verbose_name='Observação')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='children.child', verbose_name='Aventureiro')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_documents', to='documents.documenttype')),
            ],
            options={
                'verbose_name': 'Documento da Criança',
                'verbose_name_plural': 'Documentos das Crianças',
                'unique_together': {('child', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('child_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.childdocument')),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo de Documento',
                'verbose_name_plural': 'Arquivos de Documento',
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SITE', 'Site')], default='WHATSAPP', max_length=20, verbose_name='Canal')),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('RESPONDIDO', 'Respondido'), ('RESOLVIDO', 'Resolvido')], default='ENVIADO', max_length=20, verbose_name='Status')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='children.child')),
                ('sent_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('sent_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests_received', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='documents.documenttype')),
            ],
            options={
                'verbose_name': 'Solicitação de Documento',
                'verbose_name_plural': 'Solicitações de Documento',
                'ordering': ['-sent_at'],
            },
        ),
    ]
