# Generated by Django 6.0 on 2026-01-24 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='Método HTTP')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='Caminho')),
                ('view_name', models.CharField(blank=True, max_length=200, verbose_name='Nome da view')),
                ('referer', models.CharField(blank=True, max_length=500, verbose_name='Referer')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='Endereço IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Código de status')),
                ('success', models.BooleanField(db_index=True, default=True, verbose_name='Sucesso')),
                ('duration_ms', models.FloatField(blank=True, null=True, verbose_name='Duração (ms)')),
                ('message', models.TextField(blank=True, verbose_name='Detalhes')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Dados enviados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Evento de Auditoria',
                'verbose_name_plural': 'Eventos de Auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
