# Generated by Django 6.0 on 2025-12-14 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.IntegerField(default=1, verbose_name='Ordem')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='Módulo/Unidade')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_group', models.CharField(max_length=80, verbose_name='Turma/Unidade')),
                ('planned_date', models.DateField(verbose_name='Data planejada')),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('DADO', 'Dado')], default='PLANEJADO', max_length=20, verbose_name='Status')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='curriculum.contentitem')),
            ],
            options={
                'verbose_name': 'Cronograma de Conteúdo',
                'verbose_name_plural': 'Cronogramas de Conteúdo',
                'ordering': ['planned_date', 'class_group'],
                'unique_together': {('class_group', 'content_item', 'planned_date')},
            },
        ),
        migrations.CreateModel(
            name='ChildProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído')], default='NAO_INICIADO', max_length=20, verbose_name='Status')),
                ('note', models.TextField(blank=True, verbose_name='Observação')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='Marcado em')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_progress', to='children.child')),
                ('marked_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_progress', to=settings.AUTH_USER_MODEL, verbose_name='Marcado por')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_progress', to='curriculum.contentitem')),
            ],
            options={
                'verbose_name': 'Progresso do Aventureiro',
                'verbose_name_plural': 'Progressos dos Aventureiros',
                'ordering': ['-marked_at'],
                'unique_together': {('child', 'content_item')},
            },
        ),
    ]
