# Generated by Django 6.0 on 2025-12-14 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('type', models.CharField(choices=[('REUNIAO', 'Reunião'), ('EVENTO', 'Evento'), ('AULA', 'Aula')], max_length=20, verbose_name='Tipo')),
                ('class_group', models.CharField(blank=True, max_length=80, verbose_name='Turma/Unidade')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Sessão de Presença',
                'verbose_name_plural': 'Sessões de Presença',
                'ordering': ['-date', 'class_group'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False, verbose_name='Presente')),
                ('note', models.TextField(blank=True, verbose_name='Observação')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='Marcado em')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='children.child', verbose_name='Aventureiro')),
                ('marked_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL, verbose_name='Marcado por')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Registro de Presença',
                'verbose_name_plural': 'Registros de Presença',
                'ordering': ['child__name'],
                'unique_together': {('session', 'child')},
            },
        ),
    ]
